name: Devon Quispe

repo_names:
  - sex education app code

10-ux-ui-criticism:
  - https://drive.google.com/file/d/10VTGS6IJJvfsgTGMSJb6dEwLIZZFa83R/view?usp=sharing
  - https://drive.google.com/file/d/1x6lhJaRBJ169ob-BZ-VlWGrbE2JOrquj/view?usp=sharing

11-models-from-data:
  - uhhhh.com
